### ISSUE TITLE
Falha ao validar a senha

### ISSUE THREAD

**Issue by Supremo-404** [Lursy/Persux#5]
me chama no telegram t.me/napakiller

**Comment by lursy** [comment]
> me chama no telegram t.me/napakiller

Olá, boa noite. Creio que não será necessário, se não me engano você ja entrou em contato comigo pelo WhatsApp, espero que todas as questões ja tenham se resolvido, caso perceba outros problemas, por favor abra outra issue. Fico feliz em ajudar :)
